#==== gfortran (current version: gcc 4.5) ====
FC = mpif90

#-- opt or debug
#FCFLAGS = -O3 
FCFLAGS = -g -O0 -Wall -fcheck=all

#-- additional flags
FCFLAGS += -m64 -march=native -ffast-math
FCFLAGS += -fopenmp
FCFLAGS_FF = -ffixed-form
LDFLAGS = -fopenmp -lsilo -L/home/dmarce1/lib

AR = ar
RANLIB=ranlib
